-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 21:55:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gov_viagens` DEFAULT CHARACTER SET utf8 ;
USE `gov_viagens` ;

-- -----------------------------------------------------
-- Table `mydb`.`orgao_pagador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gov_viagens`.`orgao_pagador` (
  `cod_orgao_pag` INT NOT NULL AUTO_INCREMENT,
  `nome_do_orgao_pagador` VARCHAR(125) NULL,
  PRIMARY KEY (`cod_orgao_pag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orgao_solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gov_viagens`.`orgao_solicitante` (
  `cod_orgao_solic` INT NOT NULL AUTO_INCREMENT,
  `nome_orgao_solicitante` VARCHAR(125) NULL,
  PRIMARY KEY (`cod_orgao_solic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gov_viagens`.`Pagamento` (
  `id_pagam` INT NOT NULL AUTO_INCREMENT,
  `tipo_de_pagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pagam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gov_viagens`.`fato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identificador_do_processo_de_viagem` INT NULL,
  `numero_da_proposta` INT NULL DEFAULT NULL,
  `ano` INT NULL DEFAULT NULL,
  `cod_orgao_pag` INT NOT NULL,
  `cod_orgao_solic` INT NOT NULL,
  `id_pagam` INT NOT NULL,
  `valor` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `cod_orgao_pag`, `cod_orgao_solic`, `id_pagam`),
  INDEX `fk_Fato_orgao_pagador1_idx` (`cod_orgao_pag` ASC) VISIBLE,
  INDEX `fk_Fato_orgao_solicitante1_idx` (`cod_orgao_solic` ASC) VISIBLE,
  INDEX `fk_Fato_Pagamento1_idx` (`id_pagam` ASC) VISIBLE,
  CONSTRAINT `fk_Fato_orgao_pagador1`
    FOREIGN KEY (`cod_orgao_pag`)
    REFERENCES `gov_viagens`.`orgao_pagador` (`cod_orgao_pag`),
  CONSTRAINT `fk_Fato_orgao_solicitante1`
    FOREIGN KEY (`cod_orgao_solic`)
    REFERENCES `gov_viagens`.`orgao_solicitante` (`cod_orgao_solic`),
  CONSTRAINT `fk_Fato_Pagamento1`
    FOREIGN KEY (`id_pagam`)
    REFERENCES `gov_viagens`.`pagamento` (`id_pagam`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;