SELECT idviagem
FROM viagem2324
WHERE id NOT IN (SELECT idpagamento FROM pagamento2324);

ALTER TABLE viagem2324
ADD CONSTRAINT fk_idpagamentoviagem
FOREIGN KEY (id) REFERENCES pagamento2324(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE viagem2324
ADD CONSTRAINT fk_idviagempagamento
FOREIGN KEY (id) REFERENCES passagem2324(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE viagem2324
ADD CONSTRAINT fk_idviagemfato
FOREIGN KEY (id) REFERENCES fato(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

